# Makefile for Fortran project
# TQ 15 Nov 2024


# Compiler and flags
FC = gfortran
LDFLAGS = -lblas -lnetcdf -lnetcdff
FFLAGS = -finit-integer=0 -finit-real=zero -fdefault-real-8 -fdefault-integer-8 -fdefault-double-8 \
         -fimplicit-none -fno-second-underscore -fallow-argument-mismatch -cpp -ffixed-line-length-132 -fbounds-check -fbacktrace -g
DEFINES = -DNINPUT=1000 -DFPSIZE=8 -DISZ=8 -DYES=1 -DOK=0 -DDONE=1 -DSTDOUT=6 -DPi=3.141592653 -DECHARG=4.8e-10
IFLAGS = -I/opt/homebrew/Cellar/netcdf-fortran/4.6.1_1/include/ -L/opt/homebrew/opt/netcdf/lib -L/opt/homebrew/Cellar/netcdf-fortran/4.6.1_1/lib/


# Define the directories
BUILD   = build
SRC_DIR = glr
MOD_DIR = $(BUILD)/modules
OBJ_DIR = $(BUILD)/objs

# Files
# List all .F files in the source directory
SRC = $(wildcard $(SRC_DIR)/*.F)

# Convert .F files to .o files
OBJ = $(SRC:$(SRC_DIR)/%.F=$(SRC_DIR)/%.o)


# Output executable
EXEC = flora.x
MOD  = $(SRC_DIR)/flora-mod.f
MODSO = $(OBJ_DIR)/my_mod.so

.PHONY: all clean mods

# Default target: build executable
all: $(EXEC)

$(EXEC): mods $(OBJ_DIR) $(OBJ)
	@echo "Linking executable..."
	$(FC) $(MOD) $(SRC_DIR)/*.F -o $(EXEC) $(LDFLAGS) $(FFLAGS) $(DEFINES) -I$(MOD_DIR) -I$(OBJ_DIR) $(IFLAGS)
	@mv *.mod $(MOD_DIR)/

# Compile the rest of the object files
$(OBJ): %.o: %.F mods
	@echo "Compiling $@..."
	$(FC) -c $< -o $@ $(FFLAGS) $(DEFINES) -I$(MOD_DIR) $(IFLAGS)
	@mv $(SRC_DIR)/*.o $(OBJ_DIR)/

mods: $(MOD_DIR) $(OBJ_DIR)
	@echo "building modules..."
	$(FC) $(MOD) -shared -o $(MODSO) $(LDFLAGS) $(FFLAGS) $(DEFINES) $(IFLAGS)
	@mv *.mod $(MOD_DIR)/

# Ensure the MOD_DIR exists before trying to place modules in it
$(MOD_DIR):
	@echo "Creating module directory $(MOD_DIR)..."
	@mkdir -p $(MOD_DIR)

$(OBJ_DIR):
	@echo "Creating object directory $(OBJ_DIR)..."
	@mkdir -p $(OBJ_DIR)

clean:
	rm -rf $(MOD_DIR) $(OBJ_DIR)
	rm $(SRC_DIR)/*.o
	rm *.mod
	rm flora.x
